### PR TITLE
Configuration panel and CLI revamp, using the  Ace3 framework

### PR DESCRIPTION
**Pull request by bgatellier**
This PR allows to have a much more consistent behavior between the CLI and UI and improve the addon extensibility (localization, profiling...) by introducing the Ace3 framework for the configuration and some event management.

Configuration panels before:

thaliz_config_before

Configuration panel after:

thaliz_config_after

### CODE REVIEW

**Comment by bgatellier** [comment]
Most changes occur in `Core.lua` (previously Thaliz.lua) and `Core.xml` (previously Thaliz.xml)

**Comment by bgatellier** [comment]
@Sentilix I've just updated the CHANGLOG and README, as well as put my name as contributor instead of author.

Do you have time to review this PR or do you have any comment?

**Comment by bgatellier** [comment]
I duplicate this PR in order to start from a branch from my fork instead of the master branch.

**Comment by Sentilix** [comment]
Hi,

The 0.6.0 version of Thaliz is malfunction in several ways. The three most
important ones:
- Error popup when entering compat (SetPoint= - looks like some Ace3 hook
failing?
- Removing main tanks from other addons (I have no clue about this, but
probably also Ace3 related)
- Removing (deleting) a ress message gives an index error. Reloading tre UI
solves (and deletes) the message.

I am clueless for the first two - which are also the most important ones.

Do you have any suggestions how to fix?


Regards,
Tom.



Den søn. 1. nov. 2020 kl. 19.49 skrev Bastien Gatellier <
notifications@github.com>:

**Pull request closed without merging**
